### ISSUE TITLE
propose new standard names in CF table

### ISSUE THREAD

**Issue by larsbuntemeyer** [WCRP-CORDEX/data-request-table#17]
we should propose and discuss the new standard names that we have in the data request [here](https://github.com/cf-convention/discuss). If i do:

```python
import pandas as pd
from cf_xarray.utils import parse_cf_standard_name_table

table = parse_cf_standard_name_table()[1]
cf_standard_names = list(table.keys())
cf_standard_names.sort()

dr = pd.read_csv(
    "https://raw.githubusercontent.com/WCRP-CORDEX/data-request-table/main/CORDEX-CMIP6/data-request.csv"
)
cx_standard_names = list(dr.standard_name.unique())
cx_standard_names.sort()

missing = [name for name in cx_standard_names if name not in cf_standard_names]
missing
```
i get:
```
['bedrock_depth', 'lake_area_fraction', 'urban_area_fraction']
```

**Comment by larsbuntemeyer** [comment]
related issue here:

* https://github.com/cf-convention/discuss/issues/73

**Comment by larsbuntemeyer** [comment]
@gnikulin 
If there is any doubt about those variable standard names, i would maybe remove them from the data request for now until this issue is resolved...

**Comment by gnikulin** [comment]
It took time to read all long discussions in the CF issues mentioned. It seems that the right way is indeed  to use `area_fraction`as the standard name with cell methods `area: mean where lake` and `area: mean where city` for `sftlaf`and `sfturf`. The variable (`sftlaf`and `sfturf`)  and  long names (`Percentage of the Grid Cell Occupied by Lake`and `Percentage of the Grid Cell Occupied by City`) should be enough to distinguish them. We have similar cases for `mrfsos` and `mrsfl` with the same standard name `frozen_water_content_of_soil_layer` but different long names `Frozen Water Content in Upper Portion of Soil Column`and `Frozen Water Content of Soil Layer`.

**Comment by gnikulin** [comment]
What to do with `dtb` (`Depth to Bedrock`) is still a question.

**Comment by larsbuntemeyer** [comment]
Agreed, we can be more precise in the long names which are not controlled.

**Comment by larsbuntemeyer** [comment]
I opened a PR to close this issue (#22). I'll assume we'll use `bedrock_depth_below_ground_level` instead of `bedrock_depth` as discussed in https://github.com/cf-convention/discuss/issues/303.

Should we use the term `urban` instead of `city`? I think `Percentage of the Grid Cell Occupied by Urban Area` and `area where urban` is more precisely what we want, right?

**Comment by gnikulin** [comment]
Yes, `bedrock_depth_below_ground_level` has been agreed and I just formally proposed it.

We should use  `urban` instead of `city` as defined in [CF Area Type Table](https://cfconventions.org/Data/area-type-table/current/build/area-type-table.html) 

We still need to check what can be used for lakes. There is area type `fresh_free_water` but nothing like `lake`.

**Comment by larsbuntemeyer** [comment]
Ok, i think `fresh_free_water` is [supposed to also describe lakes](https://github.com/cf-convention/discuss/issues/148#issuecomment-1280064692). I would go for that for now, it seems that urban and lake modelling domains are still somewhat under discussion. I would close that PR and make a new isse so we keep it in mind.
