### ISSUE TITLE
consistent `positive` attribute

### ISSUE THREAD

**Issue by larsbuntemeyer** [WCRP-CORDEX/data-request-table#21]
from https://github.com/WCRP-CORDEX/cordex-cmip6-cmor-tables/issues/66

> The positive attribute for fluxes like hfls, hfss, rlds, rlus, etc. is not defined in the CORDEX-CMIP6 CMOR tables. Even though the standard_name includes the correct orientation, the attribute is important for the CMOR application. CMOR does not write the positive attribute to the file, but uses it to check and potentially switch the orientation.

Need to check `positive` attribute...

**Comment by gnikulin** [comment]
we simply need to define the "positive" attribute for all fluxes as in CMIP6

**Comment by larsbuntemeyer** [comment]
I'll update based the following:

* "positive : up" : ['rsus', 'rlus', 'hfls', 'hfss', 'rsuscs', 'rluscs'],
* "positive: down: ['rsds', 'rlds', 'rsdsdir', 'rsdscs', 'rldscs']")
