### ISSUE TITLE
positive attribute of `upward_air_velocity`

### ISSUE THREAD

**Issue by larsbuntemeyer** [WCRP-CORDEX/data-request-table#47]
Working on #45 , i realized that `upward_air_velocity` should probably have the `positive = up` attribute. This is not the case in the [corresponding cmip6 cmor table](https://github.com/PCMDI/cmip6-cmor-tables/blob/6a30acaea9b63fdecbe08894d7e50ef36879a993/Tables/CMIP6_AERmon.json#L2069-L2085) but i guess from the logic it should have the positive attribute set...

(all other standard names containg one of `["incoming", "outgoing", "downward", "upward", "downwelling", "upwelling", "sinking"]` are directional variables with a positive attribute set either up or down except for `upward_air_velocity`...)

**Comment by taylor13** [comment]
Yes, I agree.  We need to review all the "positive" attributes attached to up/down variables to check for consistency.  It appears that many omit designation of the direction and a few include this attribute even though they don't explicitly involve a transport/flow in the vertical direction.
